M48
; DRILL file {KiCad 8.0.1-rc1} date 2024-05-12T14:14:25-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-12T14:14:25-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-rc1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X174.445Y-107.705
X174.445Y-112.705
T2
X90.0Y-48.3
X91.0Y-123.3
X175.0Y-123.0
X179.0Y-50.0
M30
